[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lbw", email = "lbw0482@foxmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "dashscope>=1.27.7",
    "langchain>=1.4.4",
    "langchain-community>=0.4.2",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
langchain-course = "langchain_course:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
